pool:
  name: Azure Pipelines
  demands: npm

steps:
- task: uipath.vsts-uipath-package.uipath-pack.UiPathPack@4
  displayName: 'UiPath Pack'
  inputs:
    versionType: CurrentVersion
    projectJsonPath: project.json
    splitOutput: false
    orchestratorConnection: WJCICD

- task: uipath.vsts-uipath-package.uipath-deploy.UiPathDeploy@4
  displayName: 'UiPath Deploy'
  inputs:
    orchestratorConnection: WJCICD
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: WJDemo